---
title: "Differential Expression- RNA-Seq"
author: "Arjun Baghela"
date: "3/29/2017"
output: html_document
---

This is differential expression for controls vs asthma. In this script I am not doing DE on the 3 groups (Th2 high, Th2 low, and control). 

```{r}
library(edgeR)
library(DESeq2)
library(limma)
library(tidyverse)
library(magrittr)
```


```{r}
getwd()
countdata <- read.table(file= "Raw_Data/GSE85567_RNASeq_normalizedcounts.txt", check.names = FALSE)
metadata <- read.csv(file= "Raw_Data/GSE85566_metadata.txt", row.names = 1)

metadata %<>% filter(ID %in% colnames(countdata))
metadata %>% group_by(Status) %>% tally()
metadata %<>% arrange(desc(Status))

countdata <- countdata[,as.character(metadata$ID)]
colnames(countdata) == metadata$ID

```


```{r}
group <- factor(c(rep("1",28),rep("2",57))) 
DGElist <- DGEList(counts= countdata, group= group)
DGElist$samples$lib.size %>% min()
DGElist$counts %>% nrow()

keep <- rowSums(cpm(DGElist)>0.275) >= 28

DGElistFilt <- DGElist[keep, , keep.lib.sizes=FALSE]
DGElistFilt$counts %>% nrow()

DGElistFiltNorm<- calcNormFactors(DGElistFilt)
DGElistFiltNorm$samples

```

```{r}
design <- model.matrix(~group, data=DGElistFiltNorm$samples)
colnames(design) <- c("(Intercept)", "asthma")

DGElistFiltNormDisp <- estimateDisp(DGElistFiltNorm, design)
plotBCV(DGElistFiltNormDisp)
```

```{r}
fit <- glmFit(DGElistFiltNormDisp, design)
lrt <- glmLRT(fit)
DEedgeR <- topTags(lrt, n= Inf)

head(DEedgeR$table)
DEedgeR <- DEedgeR$table

DEedgeR %>% ggplot(aes(x= FDR)) + geom_histogram(binwidth= 0.05) +
	ggtitle("Adjusted P Value Distribution")

DEedgeR %>% filter(FDR <= 0.25) %>% nrow()
```

