---
title: "Pathway Enrichment"
author: "Arjun Baghela"
date: "4/3/2017"
output: html_document
---

```{r}
library(tidyverse)
library(sigora)
```


```{r}

conHigh <- readRDS("~/Desktop/team_Undecided/processed_data/controlHighResults.rds")
conLow <- readRDS("~/Desktop/team_Undecided/processed_data/controlLowResults.rds")
highLow <- readRDS("~/Desktop/team_Undecided/processed_data/highLowResults.rds")

#conHigh <- conHigh[conHigh$fdr==0,]$gene_pair %>% strsplit(".", fixed= TRUE) %>% unlist() %>% unique()

#conLow <- conLow[conLow$fdr==0,]$gene_pair %>% strsplit(".", fixed= TRUE) %>% unlist() %>% unique()

#highLow <- highLow[highLow$fdr==0,]$gene_pair %>% strsplit(".", fixed= TRUE) %>% unlist() %>% unique()

conHigh %>% filter(fdr == 0) %>% ggplot(aes(x= abs_correlation_change)) + geom_histogram(binwidth= .5)

conLow %>% filter(fdr == 0) %>% ggplot(aes(x= abs_correlation_change)) + geom_histogram(binwidth= .5)

highLow %>% filter(fdr == 0) %>% ggplot(aes(x= abs_correlation_change)) + geom_histogram(binwidth= .5)

```


```{r}
data("kegH")
sigoraResconHigh <- sigora(GPSrepo= kegH, level= 2, queryList = conHigh)
sigoraResconLow <- sigora(GPSrepo= kegH, level= 2, queryList = conLow)
sigoraReshighLow <- sigora(GPSrepo= kegH, level= 2, queryList = highLow)
```

