---
title: "WGCNA Analysis Part 2"
author: "Arjun Baghela"
date: "March 13, 2017"
output: html_document
---

```{r}
library(tidyverse)
library(magrittr)
library(edgeR)
library(DESeq2)

library(WGCNA)
options(stringsAsFactors = FALSE)
# enableWGCNAThreads() Do not run this in RStudio. Will not work. Only works in R alone. 

WGCNAnThreads()

```

```{r}
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(tcount, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")
```


```{r}
tcount_1 <- tcount
for(i in c(1:ncol(tcount_1))) {
    tcount_1[,i] <- as.numeric(tcount_1[,i])
}

str(tcount_1)
    
```


```{r}
net = blockwiseModules(tcount_1, power = 14,
TOMType = "unsigned", minModuleSize = 30,
reassignThreshold = 0, mergeCutHeight = 0.25,
numericLabels = TRUE, pamRespectsDendro = FALSE,
saveTOMs = TRUE,
saveTOMFileBase = "AsthmaFuckers",
verbose = 3)
```

