
# **** ARGUMENTS ****
dataId_arg <- "random_3" # give a meaningful name to the data generated by this specific run
repoPath_arg <- "/Users/ericchu/ws/team_Undecided/" # path to repo directory
# *******************

setwd(repoPath_arg)

directoryName <- paste0("DIFF_COR_", dataId_arg)
dataSuffix <- paste0("_", dataId_arg, ".rds")

networkMatrices <- readRDS(paste0(directoryName, "/networkMatrices", dataSuffix))
diffCorrelations <- readRDS(paste0(directoryName, "/diffCorrelations", dataSuffix))
nullDiffCorrelations <- readRDS(paste0(directoryName, "/nullDiffCorrelations", dataSuffix))
pValueMatrices <- readRDS(paste0(directoryName, "/pValueMatrices", dataSuffix))
